### ISSUE TITLE
code not working as expected

### ISSUE THREAD

**Issue by ghost** [roman01la/recursion-exercises#1]
why this code doesn't work on page, while working in the dev console @ the same time?

``` js
function sum () {
  return (function sum_iter (arr, a) {
    var a=a||0;
    if (!arr.length)
      return a;
    a+=arr.pop();
    return sum_iter(arr, a)
  })([].splice.call(arguments,0))
}
```

![screen shot 2015-10-16 at 3 18 14 pm](https://cloud.githubusercontent.com/assets/3918844/10541388/4d5e15d4-7419-11e5-9fbd-99260879f558.png)

**Comment by roman01la** [comment]
The code is being transpiled by Babel. Looks like it has a bug, I've reported it here https://github.com/babel/babel/issues/2545

However, in your code, in the inner function, you are defining a variable `a` and you also have there an argument with the same name. That's the cause.

**Comment by ghost** [comment]
removing the inner function `var` statement makes the code working, thanks for pointing that out!

**Comment by roman01la** [comment]
Looks like this code is compiled fine in newer versions of Babel. I've updated everything.
