### ISSUE TITLE
Arrow functions do not seem to work

### ISSUE THREAD

**Issue by LittleBrainz** [roman01la/recursion-exercises#2]
@roman01la...

For the "Sum" exercise, the following is accepted...

``` js
function sum(first, ...rest) {
    return first + (rest.length === 0 ? 0 : sum(...rest));
}
```

But otherwise identical code using an arrow function is rejected with a "Not recursive!" error...

``` js
const sum = (first, ...rest) => {
    return first + (rest.length === 0 ? 0 : sum(...rest));
}
```

My preferred, but also rejected, solution was simply...

``` js
const sum = (first, ...rest) => 
    first + (rest.length === 0 ? 0 : sum(...rest));
```

I am quite impressed with the interactive exercise format. I think I might nick a bit of your code.

Kind regards,

Stephen

**Comment by roman01la** [comment]
Hi. Thanks for this bug report. I'm doing code analysis via AST to determine if the function is recursive. Seems like analysis doesn't cover your case. I'll check that, thanks!

**Comment by roman01la** [comment]
The problem was caused not by arrow function usage, but by function expression instead of function declaration used as an answer function. Thanks again!
